language: python
# remove dist when trusty becomes default for real
dist: trusty
python:
 - 2.7
 - 3.3
 - 3.4
 - 3.5
 - 3.6
env:
 - PROTOBUF_VERSION=3.0.0
 - PROTOBUF_VERSION=3.2.0
 - PROTOBUF_VERSION=3.3.0
install:
 - pip install protobuf==$PROTOBUF_VERSION
 - python setup.py install
script: python -m unittest discover -v -p "unittests.py"
