language: python
python:
 - 2.7
env:
 - PROTOBUF_VERSION=2.5.0
 - PROTOBUF_VERSION=2.6.0
 - PROTOBUF_VERSION=2.6.1
install:
 - pip install protobuf==$PROTOBUF_VERSION
 - python setup.py install
script: python -m unittest discover -v -p "unittests.py"
