language: python
python:
 - 2.7
env:
 - PROTOBUF_VERSION=3.0.0
 - PROTOBUF_VERSION=3.2.0
 - PROTOBUF_VERSION=3.3.0
install:
 - pip install protobuf==$PROTOBUF_VERSION
 - python setup.py install
script: python -m unittest discover -v -p "unittests.py"
